import { Time } from "@angular/common";

export interface Idp03a188 {
        Codigo: string;
        Fecha?: Time;
        Fechaven?: Time;
        DiasSiembra: number;
        Camaron      : string   ;
        Piscina      : string   ;
        Cantidad     : number  ;
        Hectarea     : number  ;
        Densidad     : number  ;
        Laboratorio  : string   ;
        Siembra      : string   ;
        Madura       : string   ;
        Codmadura    : string   ;
        PscTransf    : string   ;
        PscTransf2   : string   ;
        PscTransf3   : string   ;
        PscTransf4   : string   ;
        PscTransf5   : string   ;
        Proyeccion   : number  ;
        Precupera    : number  ;
        Pcantidad    : number  ;
        Ppeso        : number  ;
        Pprecio      : number  ;
        Pkilos       : number  ;
        Plibras      : number  ;
        PgastosValor : number  ;
        Pventas      : number  ;
        Pgastos      : number  ;
        Putilidad    : number  ;
        Estado       : string   ;
        Peso         : number  ;
        siembratra   : string   ;
        siembratra2  : string   ;
        siembratra3  : string   ;
        siembratra4  : string   ;
        siembratra5  : string   ;
        Costo_st1    : number  ;
        Costo_st2    : number  ;
        Costo_st3    : number  ;
        Costo_st4    : number  ;
        Costo_st5    : number  ;
        Costo_st     : number  ;
        costo_larva  : number  ;    
}
